hide_window_decorations yes
cursor_shape underline
# cursor #AF69EF

font_size 14.0

include kitty-themes/themes/gruvbox_dark.conf

font_family UbuntuMono Nerd Font Mono



# BEGIN_KITTY_THEME
# Gruvbox Dark Hard
include current-theme.conf
# END_KITTY_THEME

map cmd+n no_op
